# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: "ALBERT RAY MUKIIRA"
email: "albertray132@gmail.com"
description: >-
  IT Support Professional | Comprehension of Fundamental Cybersecurity Concepts | Security Operations Center (SOC).

minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: # Optional, e.g. Africa/Nairobi

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author settings
author:
  name   : "Albert Ray Mukiira"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "IT Support Professional with a strong grasp of cybersecurity fundamentals and hands-on experience in Security Operations Center (SOC) environments. Focused on threat detection, system reliability, and continuous learning in the cybersecurity domain."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/albert-ray-mukiira"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ALBERT-CODE63"

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/albert-ray-mukiira"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ALBERT-CODE63"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archive pages
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
