# Personalized config for Albert Ray Mukiira’s portfolio site

# Site settings
title: "Albert Ray Mukiira"
email: "albertray132@gmail.com"
description: >-
  IT Support Professional | Comprehension of Fundamental Cybersecurity Concepts | Security Operations Center (SOC).

minimal_mistakes_skin: "aqua"
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Output
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author
author:
  name   : "Albert Ray Mukiira"
  avatar : "/assets/images/Passport photo.jpg"
  bio    : "Motivated IT specialist with a Diploma in ICT and certifications in cloud computing and cybersecurity. Experienced in technical support, software troubleshooting, and managing IT infrastructure. Skilled in Windows/Linux systems, user support, and deploying new technologies. Ready to bring strong technical skills and dedication to a dynamic IT team.
"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/albert-ray-mukiira"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ALBERT-CODE63"
    - label: "Download CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/files/cv.pdf"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:albertray132@gmail.com"

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/albert-ray-mukiira"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ALBERT-CODE63"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:albertray132@gmail.com"
    - label: "Download CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/images/ALBERT RAY CV..pdf"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: index
    values:
      layout: splash
      header:
        overlay_color: "#000"
        overlay_filter: "0.3"
        overlay_image: /assets/images/Passport photo.jpg
        caption: "Welcome to my professional space."
      title: "Albert Ray Mukiira"
      excerpt: "IT Support Professional | Cybersecurity Enthusiast | SOC Operations"
      author_profile: true
      buttons:
        - label: "View My CV"
          url: "/assets/images/ALBERT RAY CV..pdf"
          class: "btn btn--primary"
        - label: "Visit GitHub"
          url: "https://github.com/ALBERT-CODE63"
          class: "btn btn--success"

# Archive settings
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
